-- Run after customer_isolation_regression.sql inside the same rolled-back transaction.
reset role;
update public.users set is_active=true where user_id in (pg_temp.fixture_id('customer_user'),pg_temp.fixture_id('provider_user'));
update public.provider_profiles set verification_status='Verified' where provider_id=pg_temp.fixture_id('provider_profile');
create temporary table chat_test_ids(name text primary key,id uuid) on commit drop;
grant select,insert on chat_test_ids to authenticated;
create function pg_temp.chat_id() returns uuid language sql stable as $$ select id from pg_temp.chat_test_ids where name='chat' $$;
set local role authenticated;
select pg_temp.login_as('customer_auth','aal1');
insert into chat_test_ids values('chat',public.chat_open(pg_temp.fixture_id('provider_profile')));
select pg_temp.test_assert('chat pair is reused',public.chat_open(pg_temp.fixture_id('provider_profile'))=pg_temp.chat_id());
select pg_temp.test_assert('chat provider projection excludes private fields',not(public.chat_provider_search()->0 ? 'business_license'));
select pg_temp.test_assert('chat booking resolves same pair',public.chat_open(p_booking_id=>pg_temp.fpx_booking())=pg_temp.chat_id());
select public.chat_send(pg_temp.chat_id(),'Hello provider','dddddddd-0000-4000-8000-000000000001');
select public.chat_send(pg_temp.chat_id(),'Hello provider','dddddddd-0000-4000-8000-000000000001');
select pg_temp.test_assert('chat retry inserts once',jsonb_array_length(public.chat_history(pg_temp.chat_id())->'messages')=1);
select pg_temp.test_error('changed retry payload rejected',$$select public.chat_send(pg_temp.chat_id(),'Changed','dddddddd-0000-4000-8000-000000000001')$$,'P0001');
select pg_temp.test_error('direct message insertion denied',$$insert into public.chat_messages(conversation_id,sender_id,request_id,body) values(pg_temp.chat_id(),pg_temp.fixture_id('provider_user'),gen_random_uuid(),'Spoof')$$,'42501');
select public.chat_manage(pg_temp.chat_id(),'pin');
select pg_temp.test_assert('pin belongs to current member',public.chat_inbox()->0->>'pinned'='true');
select pg_temp.login_as('provider_auth','aal1');
select pg_temp.test_assert('provider receives unread chat',public.chat_inbox()->0->>'unread_count'='1');
select pg_temp.test_assert('customer pin does not pin provider inbox',public.chat_inbox()->0->>'pinned'='false');
select pg_temp.test_assert('provider sees customer message direction',public.chat_history(pg_temp.chat_id())->'messages'->0->>'is_mine'='false');
select public.chat_manage(pg_temp.chat_id(),'read',9223372036854775807);
select public.chat_send(pg_temp.chat_id(),'Hello customer','dddddddd-0000-4000-8000-000000000002');
select pg_temp.login_as('customer_auth','aal1');
select pg_temp.test_assert('customer receives provider reply',public.chat_history(pg_temp.chat_id())->'messages'->0->>'body'='Hello customer');
select public.chat_manage(pg_temp.chat_id(),'delete');
select pg_temp.test_assert('deleted chat hides own history',jsonb_array_length(public.chat_history(pg_temp.chat_id())->'messages')=0 and jsonb_array_length(public.chat_inbox())=0);
select pg_temp.login_as('provider_auth','aal1');
select pg_temp.test_assert('delete preserves other participant history',jsonb_array_length(public.chat_history(pg_temp.chat_id())->'messages')=2);
select public.chat_send(pg_temp.chat_id(),'A new reply','dddddddd-0000-4000-8000-000000000003');
select pg_temp.login_as('customer_auth','aal1');
select pg_temp.test_assert('new incoming message restores chat without cleared history',jsonb_array_length(public.chat_inbox())=1 and jsonb_array_length(public.chat_history(pg_temp.chat_id())->'messages')=1);
select public.chat_manage(pg_temp.chat_id(),'block');
select public.chat_manage(pg_temp.chat_id(),'delete');
select pg_temp.test_assert('deleted blocked chat remains reachable to unblock',public.chat_blocked()->0->>'conversation_id'=pg_temp.chat_id()::text);
select pg_temp.login_as('provider_auth','aal1');
select pg_temp.test_error('block prevents peer sending',$$select public.chat_send(pg_temp.chat_id(),'Blocked','dddddddd-0000-4000-8000-000000000004')$$,'P0001');
select pg_temp.login_as('customer_auth','aal1');
select public.chat_manage(pg_temp.chat_id(),'unblock');
select public.customer_account_update('Customer profile test','+601000000001',array['Cleaning'],null,'Private bio','Prefer not to say','2000-01-01');
select pg_temp.test_assert('extended profile saved atomically',(select bio='Private bio' and birthday=date '2000-01-01' from public.customer_profiles where customer_id=pg_temp.fixture_id('customer_profile')));
select pg_temp.test_error('profile rejects malformed Malaysia number',$$select public.customer_account_update('Bad','+6500000000',array[]::text[])$$,'P0001');
select pg_temp.test_error('profile rejects future birthday',$$select public.customer_account_update('Bad','+601000000001',array[]::text[],null,null,null,current_date+1)$$,'P0001');
select set_config('request.jwt.claim.sub','eeeeeeee-0000-4000-8000-000000000021',true);
select set_config('request.jwt.claims','{"sub":"eeeeeeee-0000-4000-8000-000000000021","role":"authenticated","aal":"aal1"}',true);
select pg_temp.test_assert('other customer cannot list blocked chats',jsonb_array_length(public.chat_blocked())=0);
select pg_temp.test_assert('other customer sees no chat rows',not exists(select 1 from public.chat_messages where conversation_id=pg_temp.chat_id()) and not exists(select 1 from public.chat_conversations where conversation_id=pg_temp.chat_id()));
select pg_temp.test_error('other customer cannot read chat','select public.chat_history(pg_temp.chat_id())','42501');
select pg_temp.test_error('other customer cannot send chat',$$select public.chat_send(pg_temp.chat_id(),'Intruder','dddddddd-0000-4000-8000-000000000005')$$,'42501');
select pg_temp.test_error('other customer cannot pin chat',$$select public.chat_manage(pg_temp.chat_id(),'pin')$$,'42501');
select pg_temp.test_error('other customer cannot open someone else booking','select public.chat_open(p_booking_id=>pg_temp.fpx_booking())','42501');
reset role;
select pg_temp.test_assert('failed profile mutation rolled back',(select full_name='Customer profile test' from public.users where user_id=pg_temp.fixture_id('customer_user')));
select jsonb_build_object('passed',count(*)) as all_regressions from pg_temp.admin_regression_results;
