-- Run after the existing regression suites, within rollback-only fixtures.
reset role;
set local role authenticated;
select pg_temp.login_as('customer_auth','aal1');
select pg_temp.test_error('recovery lookup is server only',$$select public.customer_recovery_check('test@example.invalid',repeat('a',64))$$,'42501');
select pg_temp.test_assert('badge count is customer scoped', (public.customer_unread_counts()->>'notifications')::bigint=(select count(*) from public.notifications where user_id=pg_temp.fixture_id('customer_user') and not is_read and dismissed_at is null));
select pg_temp.login_as('provider_auth','aal1');
select public.chat_send(pg_temp.chat_id(),'Badge incoming fixture','dddddddd-0000-4000-8000-000000000099');
select pg_temp.login_as('customer_auth','aal1');
select pg_temp.test_assert('badge counts new incoming chat',(public.customer_unread_counts()->>'chats')::bigint=1);
select public.chat_manage(pg_temp.chat_id(),'read',9223372036854775807);
select pg_temp.test_assert('badge clears after chat is read',(public.customer_unread_counts()->>'chats')::bigint=0);
update public.notifications set is_read=true where user_id=pg_temp.fixture_id('customer_user') and booking_id is not null and not is_read;
select pg_temp.test_assert('booking badge clears after updates read',(public.customer_unread_counts()->>'bookings')::bigint=0);
select public.customer_save_address('Home','Activity fixture one','Kuala Lumpur','Kuala Lumpur','50088',3.15,101.71,true);
select public.customer_save_address('Office','Activity fixture two','Kuala Lumpur','Kuala Lumpur','50088',3.15,101.71,false);
select public.customer_set_default_address((select address_id from public.saved_addresses where address_line='Activity fixture two'));
select pg_temp.test_assert('default switch keeps one address', (select count(*)=1 from public.saved_addresses where customer_id=pg_temp.fixture_id('customer_profile') and is_default));
select pg_temp.test_assert('address change is recorded', exists(select 1 from public.notifications where title='Default address changed' and user_id=pg_temp.fixture_id('customer_user')));
select public.customer_delete_address((select address_id from public.saved_addresses where address_line='Activity fixture two'));
select pg_temp.test_assert('address deletion is recorded',exists(select 1 from public.notifications where title='Address deleted' and user_id=pg_temp.fixture_id('customer_user')));
select pg_temp.test_assert('deleting default selects replacement',(select count(*)=1 from public.saved_addresses where customer_id=pg_temp.fixture_id('customer_profile') and is_default));
update public.users set full_name='Activity updated customer' where user_id=pg_temp.fixture_id('customer_user');
select pg_temp.test_assert('personal info recorded',exists(select 1 from public.notifications where title='Personal information updated' and user_id=pg_temp.fixture_id('customer_user')));
reset role;
select pg_temp.test_assert('unknown recovery email rejected', (public.customer_recovery_check('__missing_activity_fixture@example.invalid',repeat('a',64))->>'registered')::boolean=false);
select pg_temp.test_assert('registered recovery email accepted', (public.customer_recovery_check((select email from auth.users where id=pg_temp.fixture_id('customer_auth')),repeat('b',64))->>'registered')::boolean=true);
select pg_temp.test_assert('provider cannot use customer recovery', (public.customer_recovery_check((select email from auth.users where id=pg_temp.fixture_id('provider_auth')),repeat('c',64))->>'registered')::boolean=false);
do $$begin for i in 1..5 loop perform public.customer_recovery_check('__missing_activity_fixture@example.invalid',repeat('a',64)); end loop; end $$;
select pg_temp.test_assert('recovery throttles repeated lookup',(public.customer_recovery_check('__missing_activity_fixture@example.invalid',repeat('a',64))->>'allowed')::boolean=false);
update auth.users set encrypted_password='fixture-hash-changed' where id=pg_temp.fixture_id('customer_auth');
select pg_temp.test_assert('password activity recorded',exists(select 1 from public.notifications where title='Password changed' and user_id=pg_temp.fixture_id('customer_user')));
set local role authenticated;
select pg_temp.login_as('provider_auth','aal1');
select pg_temp.test_error('provider cannot query customer badges',$$select public.customer_unread_counts()$$,'42501');
reset role;
