<?php declare(strict_types=1); ?>
<?php if ($page==='login'): ?>
    <span class="eyebrow">ADMIN PORTAL</span><h1>Welcome back.</h1><p class="auth-intro">Sign in to take care of your service community.</p>
    <form method="post" action="<?= e(url('login')) ?>" class="stack-form"><?= viewFields('login') ?>
        <div><label for="email">Email address</label><input type="email" id="email" name="email" required autocomplete="username" maxlength="254" placeholder="you@example.com" value="<?= e($_POST['email'] ?? '') ?>"></div>
        <div><div class="label-row"><label for="password">Password</label><a href="<?= e(url('forgot')) ?>" class="text-link">Forgot password?</a></div><div class="password-field"><input type="password" id="password" name="password" required autocomplete="current-password" maxlength="128"><button type="button" class="icon-button password-toggle" data-password="password" aria-label="Show password" aria-pressed="false"><?= viewIcon('eye') ?></button></div></div>
        <button class="button button-primary button-full" type="submit">Sign in <?= viewIcon('arrow') ?></button>
    </form><p class="auth-note">Access is available to invited administrators only. Customer and provider accounts use the mobile app.</p><p class="activation-note">First time here? <a href="<?= e(url('signup')) ?>" class="text-link">Activate your admin account</a></p>
<?php elseif ($page==='signup'): ?>
    <a class="back-link" href="<?= e(url('login')) ?>">← Back to sign in</a><span class="eyebrow">INVITED ADMINISTRATORS</span><h1>Welcome to the team.</h1><p class="auth-intro">Use your invited email to activate your admin account. Access is granted only to preapproved administrators.</p>
    <form class="stack-form" method="post" action="<?= e(url('signup')) ?>"><?= viewFields('signup') ?><div><label for="email">Invited email address</label><input id="email" name="email" type="email" autocomplete="username" maxlength="254" required value="<?= e($_POST['email'] ?? '') ?>" placeholder="you@example.com"></div><div><label for="password">Create password</label><div class="password-field"><input id="password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><button type="button" class="icon-button password-toggle" data-password="password" aria-label="Show password" aria-pressed="false"><?= viewIcon('eye') ?></button></div><p class="field-note">Use 12–128 characters. Keep this password private.</p></div><div><label for="confirm">Confirm password</label><input id="confirm" name="confirm" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><button class="button button-primary button-full">Activate account <?= viewIcon('arrow') ?></button></form><p class="auth-note">After activation, verify your email and set up an authenticator to complete secure access.</p>
<?php elseif ($page==='forgot'): ?>
    <a class="back-link" href="<?= e(url('login')) ?>">← Back to sign in</a><span class="eyebrow">ACCOUNT RECOVERY</span><h1>Forgot your password?</h1><p class="auth-intro">Enter your admin email and we’ll send a link to choose a new password.</p>
    <form class="stack-form" method="post" action="<?= e(url('forgot')) ?>"><?= viewFields('recover') ?><div><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="username" maxlength="254" required value="<?= e($_POST['email'] ?? '') ?>" placeholder="you@example.com"></div><button class="button button-primary button-full">Send reset link <?= viewIcon('arrow') ?></button></form><p class="auth-note">For your security, open the email link in the same browser where you requested it.</p>
<?php elseif ($page==='reset'): ?>
    <span class="eyebrow">ACCOUNT RECOVERY</span><h1>A fresh start.</h1><p class="auth-intro">Choose a strong, unique password for your admin account.</p>
    <form class="stack-form" method="post" action="<?= e(url('reset')) ?>"><?= viewFields('reset') ?><div><label for="password">New password</label><div class="password-field"><input id="password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><button class="icon-button password-toggle" type="button" data-password="password" aria-label="Show password" aria-pressed="false"><?= viewIcon('eye') ?></button></div><p class="field-note">Use 12–128 characters. A memorable passphrase works well.</p></div><div><label for="confirm">Confirm new password</label><input id="confirm" name="confirm" type="password" autocomplete="new-password" minlength="12" maxlength="128" required></div><button class="button button-primary button-full">Update password <?= viewIcon('arrow') ?></button></form>
<?php elseif ($page==='mfa'): ?>
    <div class="auth-icon"><?= viewIcon('shield') ?></div><span class="eyebrow">TWO-STEP VERIFICATION</span><h1><?= $factors?'One more step.':'Protect your account.' ?></h1>
    <?php if ($factors): ?><p class="auth-intro">Enter the six-digit code from your authenticator app.</p><form class="stack-form" method="post" action="<?= e(url('mfa')) ?>"><?= viewFields('verify') ?><?php if(count($factors)>1): ?><div><label for="factor_id">Authenticator</label><select id="factor_id" name="factor_id" required><?php foreach($factors as $factor): ?><option value="<?= e($factor['id']) ?>"><?= e($factor['friendly_name'] ?? 'Authenticator') ?></option><?php endforeach; ?></select></div><?php else: ?><input type="hidden" name="factor_id" value="<?= e($factors[0]['id']) ?>"><?php endif; ?><div><label for="code">Verification code</label><input class="code-input" id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="000000" autofocus></div><button class="button button-primary button-full">Verify & continue <?= viewIcon('arrow') ?></button></form>
    <?php elseif (!empty($_SESSION['enrollment'])): $enrollment=$_SESSION['enrollment']; ?><p class="auth-intro">Scan this code with an authenticator app, then enter the code it generates.</p><div class="qr-wrap"><?php $qr=(string)($enrollment['totp']['qr_code'] ?? ''); if(str_starts_with($qr,'data:image/')): ?><img src="<?= e($qr) ?>" width="190" height="190" alt="Authenticator setup QR code"><?php elseif(str_starts_with(ltrim($qr),'<svg')): ?><img src="data:image/svg+xml;base64,<?= e(base64_encode($qr)) ?>" width="190" height="190" alt="Authenticator setup QR code"><?php endif; ?></div><details class="setup-key"><summary>Can’t scan the code?</summary><p>Enter this setup key in your authenticator:</p><code><?= e($enrollment['totp']['secret'] ?? '') ?></code></details><form class="stack-form" method="post" action="<?= e(url('mfa')) ?>"><?= viewFields('verify') ?><input type="hidden" name="factor_id" value="<?= e($enrollment['id']) ?>"><div><label for="code">Verification code</label><input class="code-input" id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="000000"></div><button class="button button-primary button-full">Complete setup <?= viewIcon('arrow') ?></button></form>
    <?php else: ?><p class="auth-intro">Add an authenticator app to protect access to customer records and admin actions.</p><div class="info-card"><strong>What you’ll need</strong><p>An authenticator app on your phone. Setup takes about a minute and codes work without a mobile connection.</p></div><form method="post" action="<?= e(url('mfa')) ?>"><?= viewFields('enroll') ?><button class="button button-primary button-full">Set up authenticator <?= viewIcon('arrow') ?></button></form><?php endif; ?>
    <form class="auth-signout" method="post" action="<?= e(url('mfa')) ?>"><?= viewFields('logout') ?><button class="text-button">Sign out and use another account</button></form>
<?php else: ?><span class="eyebrow">ACCOUNT RECOVERY</span><h1>Recovery link unavailable.</h1><p class="auth-intro">Request a new link and open it in this browser to continue.</p><a class="button button-primary" href="<?= e(url('forgot')) ?>">Request a new link <?= viewIcon('arrow') ?></a><?php endif; ?>
