<?php
declare(strict_types=1);
$items=$data['items'] ?? []; $total=(int)($data['total'] ?? 0); $currentPage=(int)($data['page'] ?? 1); $pageSize=(int)($data['page_size'] ?? 20); $pageCount=max(1,(int)ceil($total/max(1,$pageSize)));
$filters=['users'=>['Active','Suspended'],'providers'=>['Pending','Verified','Rejected','Suspended'],'categories'=>['Active','Inactive'],'bookings'=>['Pending','Confirmed','In-Progress','Completed','Cancelled'],'reviews'=>['Visible','Flagged','Hidden'],'disputes'=>['Open','Under Review','Resolved','Dismissed'],'refunds'=>['Requested','Processing','Succeeded','Failed','Cancelled']];
$ids=['users'=>'user_id','providers'=>'provider_id','categories'=>'category_id','bookings'=>'booking_id','reviews'=>'review_id','disputes'=>'dispute_id','refunds'=>'refund_id','audit'=>'log_id'];
$supportsDetail=in_array($page,['users','providers','categories','bookings','reviews','disputes'],true);
$columns=['users'=>['User','Role','Account status','Joined'],'providers'=>['Provider','Location','Verification','Submitted'],'categories'=>['Category','Parent','Services','Status'],'bookings'=>['Service & customer','Provider','Scheduled','Status','Amount'],'reviews'=>['Customer & provider','Rating','Feedback','Status'],'disputes'=>['Issue','Booking','Opened by','Status','Opened'],'refunds'=>['Request','Booking','Amount','Status','Requested'],'audit'=>['Action','Administrator','Record','Time','Changes']];
?>
<section class="panel resource-panel" aria-labelledby="records-title">
    <div class="panel-heading"><div><h2 id="records-title"><?= e($titles[$page]) ?> <span class="count-tag"><?= number_format($total) ?></span></h2><p><?= $page==='refunds'?'A request records an intended refund; funds move only when the payment gateway processes it.':($page==='audit'?'A permanent record of administrative changes.':'Search and review your records.') ?></p></div><?php if($page==='bookings'): ?><div class="report-actions"><a class="button button-secondary button-small" href="<?= e(url('bookings',['q'=>$_GET['q'] ?? '','status'=>$_GET['status'] ?? '','export'=>'print'])) ?>" target="_blank" rel="noopener noreferrer">Print / Save PDF</a><a class="button button-secondary button-small" href="<?= e(url('bookings',['q'=>$_GET['q'] ?? '','status'=>$_GET['status'] ?? '','export'=>'1'])) ?>"><?= viewIcon('download') ?> Export CSV</a></div><?php endif; ?></div>
    <form class="filter-bar" method="get" action="/"><input type="hidden" name="page" value="<?= e($page) ?>"><div class="search-field"><?= viewIcon('search') ?><label class="sr-only" for="search">Search <?= e($titles[$page]) ?></label><input id="search" type="search" name="q" value="<?= e($_GET['q'] ?? '') ?>" placeholder="Search <?= e(strtolower($titles[$page])) ?>…" maxlength="100"></div><?php if(isset($filters[$page])): ?><label class="sr-only" for="status-filter">Filter by status</label><select id="status-filter" name="status"><option value="">All statuses</option><?php foreach($filters[$page] as $option): ?><option value="<?= e($option) ?>" <?= ($_GET['status'] ?? '')===$option?'selected':'' ?>><?= e($option) ?></option><?php endforeach; ?></select><?php endif; ?><button type="submit" class="button button-secondary button-small">Apply filters</button><?php if(!empty($_GET['q']) || !empty($_GET['status'])): ?><a class="text-link" href="<?= e(url($page)) ?>">Clear</a><?php endif; ?></form>
    <?php if(!$items): ?><div class="empty-state"><span class="empty-icon"><?= viewIcon($navigation[$page][1]) ?></span><h3><?= !empty($_GET['q']) || !empty($_GET['status'])?'No matching records':'No '.e(strtolower($navigation[$page][0])).' yet' ?></h3><p><?= !empty($_GET['q']) || !empty($_GET['status'])?'Try a different search or clear the filters.':'Records will appear here when they are created in your service community.' ?></p><?php if($page==='categories'): ?><a class="button button-primary" href="<?= e(url('categories',['new'=>'1'])) ?>"><?= viewIcon('plus') ?> Create a category</a><?php endif; ?></div>
    <?php else: ?><div class="table-wrap"><table><thead><tr><?php foreach($columns[$page] as $column): ?><th scope="col"><?= e($column) ?></th><?php endforeach; ?><?php if($supportsDetail): ?><th scope="col"><span class="sr-only">Details</span></th><?php endif; ?></tr></thead><tbody>
    <?php foreach($items as $item): $id=(string)($item[$ids[$page]] ?? ''); ?><tr <?= $detail && ($detail[$ids[$page]] ?? '')===$id?'class="selected-row"':'' ?>>
        <?php if($page==='users'): ?><td><div class="person-cell"><span class="table-avatar"><?= e(strtoupper(mb_substr($item['full_name'] ?? '?',0,1))) ?></span><div><strong><?= e($item['full_name']) ?></strong><span><?= e($item['email']) ?></span></div></div></td><td><span class="role-text"><?= e(ucfirst((string)$item['role'])) ?></span></td><td><?= badge($item['status']) ?></td><td class="muted"><?= e(localDate($item['created_at'],'d M Y')) ?></td>
        <?php elseif($page==='providers'): ?><td><strong><?= e($item['business_name']) ?></strong><span class="cell-sub"><?= e($item['full_name']) ?></span></td><td><?= e(trim(($item['city'] ?? '').', '.($item['region'] ?? ''),', ') ?: 'Not supplied') ?></td><td><?= badge($item['verification_status']) ?></td><td class="muted"><?= e(localDate($item['created_at'],'d M Y')) ?></td>
        <?php elseif($page==='categories'): ?><td><strong><?= e($item['category_name']) ?></strong><span class="cell-sub"><?= e(mb_strimwidth((string)($item['description'] ?? ''),0,90,'…')) ?></span></td><td><?= e($item['parent_name'] ?? 'Top-level category') ?></td><td><?= number_format((int)$item['service_count']) ?></td><td><?= badge($item['status']) ?></td>
        <?php elseif($page==='bookings'): ?><td><strong><?= e($item['service_name']) ?></strong><span class="cell-sub"><?= e($item['customer_name']) ?></span><code class="record-code"><?= e(mb_substr($id,0,8)) ?></code></td><td><?= e($item['provider_name']) ?></td><td><?= e(localDate($item['scheduled_datetime'])) ?></td><td><?= badge($item['booking_status']) ?><span class="cell-sub">Payment: <?= e($item['payment_status'] ?? 'Not recorded') ?></span></td><td class="amount"><?= e(money($item['total_amount'])) ?></td>
        <?php elseif($page==='reviews'): ?><td><strong><?= e($item['customer_name']) ?></strong><span class="cell-sub"><?= e($item['provider_name']) ?></span></td><td><span class="rating-stars" aria-label="<?= e($item['rating_score']) ?> out of 5">★ <strong><?= e($item['rating_score']) ?></strong></span></td><td class="feedback-cell"><?= e(mb_strimwidth((string)($item['review_comment'] ?? ''),0,130,'…') ?: 'No written feedback') ?></td><td><?= badge($item['status']) ?></td>
        <?php elseif($page==='disputes'): ?><td><strong><?= e($item['subject']) ?></strong><span class="cell-sub"><?= e(mb_strimwidth((string)$item['description'],0,90,'…')) ?></span></td><td><a class="text-link" href="<?= e(url('bookings',['id'=>$item['booking_id']])) ?>"><code><?= e(mb_substr($item['booking_id'],0,8)) ?></code></a></td><td><?= e($item['opened_by_name']) ?></td><td><?= badge($item['status']) ?></td><td class="muted"><?= e(localDate($item['created_at'],'d M Y')) ?></td>
        <?php elseif($page==='refunds'): ?><td><code><?= e(mb_substr($id,0,8)) ?></code><span class="cell-sub"><?= e(mb_strimwidth((string)$item['reason'],0,90,'…')) ?></span></td><td><a class="text-link" href="<?= e(url('bookings',['id'=>$item['booking_id']])) ?>"><code><?= e(mb_substr($item['booking_id'],0,8)) ?></code></a></td><td class="amount"><?= e(money($item['amount'])) ?></td><td><?= badge($item['status']) ?><?php if(!empty($item['gateway_reference'])): ?><span class="cell-sub"><?= e($item['gateway_reference']) ?></span><?php endif; ?></td><td class="muted"><?= e(localDate($item['created_at'])) ?></td>
        <?php else: ?><td><strong><?= e(ucwords(str_replace('_',' ',$item['action']))) ?></strong></td><td><?= e($item['actor_name'] ?? 'System') ?><span class="cell-sub"><?= e($item['actor_role'] ?? '') ?></span></td><td><?= e($item['target_table']) ?><code class="cell-sub"><?= e(mb_substr((string)($item['target_id'] ?? ''),0,8)) ?></code></td><td class="muted"><?= e(localDate($item['created_at'])) ?></td><td><details class="audit-details"><summary>View changes</summary><strong>Before</strong><pre><?= e(json_encode($item['old_values'] ?? [],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?></pre><strong>After</strong><pre><?= e(json_encode($item['new_values'] ?? [],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?></pre></details></td>
        <?php endif; ?>
        <?php if($supportsDetail): ?><td class="action-cell"><a class="row-action" href="<?= e(url($page,['id'=>$id,'q'=>$_GET['q'] ?? '','status'=>$_GET['status'] ?? '','p'=>$currentPage])) ?>#record-detail" aria-label="View <?= e($page) ?> record <?= e(mb_substr($id,0,8)) ?>">View <?= viewIcon('arrow') ?></a></td><?php endif; ?>
    </tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
    <div class="pagination"><p><?= $total?number_format(($currentPage-1)*$pageSize+1).'–'.number_format(min($currentPage*$pageSize,$total)).' of '.number_format($total).' records':'0 records' ?></p><div><span>Page <?= $currentPage ?> of <?= $pageCount ?></span><?php if($currentPage>1): ?><a class="button button-secondary button-small" href="<?= e(url($page,['q'=>$_GET['q'] ?? '','status'=>$_GET['status'] ?? '','p'=>$currentPage-1])) ?>">Previous</a><?php endif; ?><?php if($currentPage<$pageCount): ?><a class="button button-secondary button-small" href="<?= e(url($page,['q'=>$_GET['q'] ?? '','status'=>$_GET['status'] ?? '','p'=>$currentPage+1])) ?>">Next</a><?php endif; ?></div></div>
</section>
<?php if($detail || ($page==='categories' && isset($_GET['new']))): require __DIR__.'/detail.php'; endif; ?>
